[package]
name = "subway-surfers-rust"
version = "1.2.0"
authors = ["gabrielklbr"]

[[bin]]
name = "SubwaySurfersRust"
path = "src/main.rs"

[build-dependencies]
winres = "0.1.12"
cc = "1.2.44"

[dependencies]
tiny_http = "0.12.0"